"""add is_available column to matches

Revision ID: 17f2cc45c9d8
Revises: 4ab0b6181b6e
Create Date: 2026-08-19 18:53:11.244983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f2cc45c9d8'
down_revision: Union[str, Sequence[str], None] = '4ab0b6181b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'match', 
        sa.Column('is_bet_available', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'is_bet_available')
    # ### end Alembic commands ###
